powerhome/power-tools

- .github/CODEOWNERS
CODEOWNERS prevent renovate automerge since it will automatically ask for review
See documentation for more details: https://docs.renovatebot.com/automerge-configuration/
Solution: make files used by renovate owned by everyone
> Allow renovate-automerge to operate

- packages/lumberaxe/docs/CHANGELOG.md
- packages/lumberaxe/lib/lumberaxe.rb
- packages/lumberaxe/lib/lumberaxe/version.rb
- packages/lumberaxe/spec/lumberaxe/lumberaxe_spec.rb
Unfortunately the `to_json` method is imported either by the `json` or `rails` libraries; ruby has no native way to convert this. 
This line was failing in environments where rails was not (or not _yet_) loaded.
> Ensure hashes can be converted to json

- packages/audit_tracker/spec/audit_tracker_spec.rb
- packages/consent/spec/consent/ability_spec.rb
- packages/consent/spec/consent/model_additions_spec.rb
- packages/consent/spec/consent/permission_migration_spec.rb
- packages/consent/spec/models/authorizable_spec.rb
- packages/consent/spec/models/permission_spec.rb
Not sure how these got onto the main branch, but they're making specs fail on PRs.
Example: https://github.com/powerhome/power-tools/actions/runs/3669714516/jobs/6203741959
> Autocorrect rubocop failures

- packages/edgestitch/lib/edgestitch/mysql/dump.rb
- packages/edgestitch/lib/edgestitch/version.rb
Not setting this option leaves to the server configuration to decide, making it error prone depending on the user config. This option is not necessary for our database dump.
Also, enabling this might cause table locks:
> The data and the GTIDs backed up by mysqldump were inconsistent when the options --single-transaction and --set-gtid-purged=ON were both used. It was because in between the transaction started by mysqldump and the fetching of GTID_EXECUTED, GTIDs on the server could have increased already. With this fixed, a FLUSH TABLES WITH READ LOCK is performed before the fetching of GTID_EXECUTED to ensure its value is consistent with the snapshot taken by mysqldump.
>
> Our thanks to Marcelo Altmann for the contribution. (Bug #33630199)
This is documented as:
> Closes all open …
> Set GTID purged OFF to avoid table locks

- packages/edgestitch/lib/edgestitch/tasks.rb
Allow disabling the rails tasks enhancements
A new version of mysqldump broke the generation of database dumps when GTID is enabled. This allow us to disable the db:stitch task enhancement on top of db:migrate when in deployment, where that is not necessary.
> Allow disabling rails tasks enhancing

- packages/edgestitch/lib/edgestitch/mysql/dump.rb
- packages/edgestitch/lib/edgestitch/version.rb
Locking tables is not desirable behavior for powerhome's infrastructure (and many others tbh)
From manpage:
```
8.0.31:
--single-transaction
Creates a consistent snapshot by dumping all tables in a
single transaction. Works ONLY for tables stored in
storage engines which support multiversioning (currently
only InnoDB does); the dump is NOT guaranteed to be
consistent for other storage engines. While a
--single-transaction dump is in process, to ensure a
valid dump file (correct table contents and binary log
position), no other connection should use the following
statements: ALTER TABLE, DROP TABLE, RENAME TABLE,
TRUNCATE TABLE, as consistent snapshot is not isolated
from them. Option automatically turns off --lock-tables.
```
We do not believe that this level of protection from dumping an …
> Remove `single-transaction` in attempt to stop read lock

- docs/README.md
- packages/eslint-config/README.md
NPM packages require a README file at the root level of the package: https://docs.npmjs.com/about-package-readme-files
This PR attempts to display the existing docs/README file through a symlink. If that doesn't work, it's possible to add a script to the publishing process to copy over the file.
> Add readme to npm

- .github/workflows/eslint-config.yml
- packages/eslint-config/README.md
- packages/eslint-config/package.json
Adding a symlink to the README in the root folder was not allowed by NPM. So, let's copy the file to the root while publishing.
> Copy readme to root folder

- packages/cygnet/Gemfile.lock
- packages/rabbet/Gemfile.lock
- packages/rubocop-cobra/CHANGELOG.md
- packages/rubocop-cobra/Gemfile.lock
- packages/rubocop-cobra/lib/rubocop/cobra/version.rb
- packages/rubocop-cobra/rubocop-cobra.gemspec
- packages/rubocop-powerhome/CHANGELOG.md
- packages/rubocop-powerhome/lib/rubocop/powerhome/version.rb
- packages/rubocop-powerhome/rubocop-powerhome.gemspec
The bug that caused all the drama [was fixed already](https://github.com/rubocop/rubocop/issues/11549).
> Allow new rubocop versions

- .github/workflows/_ruby-package.yml
Reverts powerhome/power-tools#102 because it wasn't a valid fix.
> Revert "Work around bundler "dubious ownership" error"

- packages/rubocop-powerhome/lib/rubocop-powerhome.rb
Loading a rubocop extension is nothing but requiring a library, but rubocop likes to know what's loaded
so it can suggest you extensions that are loaded but not used.
https://github.com/rubocop/rubocop/blob/02c32b4cf3801f9cf4cca4b3f1f4288aaee2ad5c/lib/rubocop/options.rb#L304
> Inform RuboCop about loaded extensions

- packages/lumberaxe/lib/lumberaxe/json_formatter.rb
- packages/lumberaxe/spec/lumberaxe/lumberaxe_spec.rb
Mainly just restores the JSON formatter to its old `LogChooser` algorithm:
https://github.com/powerhome/power-tools/pull/19/commits/c5f52dc93#diff-b5c693951741188b864854a97fd5cdc4eaa20c335ae29492f2c36d7877bb4965L29-L36
> Fixes tagged logging

- .github/workflows/lumberaxe.yml
- packages/lumberaxe/Appraisals
- packages/lumberaxe/Gemfile.lock
- packages/lumberaxe/gemfiles/rails_6_0.gemfile
- packages/lumberaxe/gemfiles/rails_6_0.gemfile.lock
- packages/lumberaxe/gemfiles/rails_6_1.gemfile
- packages/lumberaxe/gemfiles/rails_6_1.gemfile.lock
- packages/lumberaxe/gemfiles/rails_7_0.gemfile.lock
- packages/lumberaxe/gemfiles/rails_7_1.gemfile
- packages/lumberaxe/gemfiles/rails_7_1.gemfile.lock
- packages/lumberaxe/lumberaxe.gemspec
To address the [dependency conflict](https://github.com/powerhome/example-rails-app/pull/335) in the `example-rails-app` application, the team @powerhome/forever-people proposes upgrading the [rails gem to version 7.1.3](https://rubygems.org/gems/rails).
> Upgrade the Rails version to 7.1.3 for the lumberaxe library.

- packages/dep_shield/Gemfile.lock
- packages/dep_shield/lib/dep_shield/todos.rb
- packages/dep_shield/lib/dep_shield/version.rb
- packages/dep_shield/spec/internal/config/extra/.deprecation_todo.yml
Sometimes calling `YAML.load_file` on an empty file returns `nil`. Other times, it returns `false`. This accounts for both.
> DepShield: Navigate around multiple returns

- packages/edgestitch/Gemfile.lock
- packages/edgestitch/docs/CHANGELOG.md
- packages/edgestitch/gemfiles/rails_6_0.gemfile.lock
- packages/edgestitch/gemfiles/rails_6_1.gemfile.lock
- packages/edgestitch/gemfiles/rails_7_0.gemfile.lock
- packages/edgestitch/lib/edgestitch/mysql/dump.rb
- packages/edgestitch/lib/edgestitch/version.rb
- packages/edgestitch/spec/dummy/config/application.rb
- packages/edgestitch/spec/edgestitch/mysql/dump_spec.rb
Minimize merge conflicts
Based on:
https://github.com/lfittl/activerecord-clean-db-structure
- Extract sanitize_migration_timestamps to mysql
- Minimize conflicts in schema migrations
- Always load the defaults for the current version being tested
> Minimize conflicts

- packages/dep_shield/CHANGELOG.md
- packages/dep_shield/Gemfile.lock
- packages/dep_shield/dep_shield.gemspec
- packages/dep_shield/gemfiles/rails_6_0.gemfile.lock
- packages/dep_shield/gemfiles/rails_6_1.gemfile.lock
- packages/dep_shield/gemfiles/rails_7_0.gemfile.lock
- packages/dep_shield/lib/dep_shield.rb
- packages/dep_shield/lib/dep_shield/version.rb
- packages/dep_shield/spec/spec_helper.rb
- Remove optional dependency "railties" (users of the railtie include the railtie)
- remove unused dependency "sentry-rails"
- Remove require of `rails/all`
> Cleanup dep_shield dependencies including all of rails

- packages/data_taster/Gemfile.lock
- packages/data_taster/docs/CHANGELOG.md
- packages/data_taster/gemfiles/rails_6_0.gemfile.lock
- packages/data_taster/gemfiles/rails_6_1.gemfile.lock
- packages/data_taster/gemfiles/rails_7_0.gemfile.lock
- packages/data_taster/lib/data_taster/flavors.rb
- packages/data_taster/lib/data_taster/version.rb
Rails 7.0 depreated the use of `to_s` for date formatting, in favor of `to_fs` or `to_formatted_s`, being the later present in more versions of rails.
- **Fix DataTasterFlavors#date**
- **Bump DataTaster version**
> Fix data taster flavor date

- packages/data_taster/Gemfile.lock
- packages/data_taster/data_taster.gemspec
- packages/data_taster/docs/CHANGELOG.md
- packages/data_taster/gemfiles/rails_6_0.gemfile.lock
- packages/data_taster/gemfiles/rails_6_1.gemfile.lock
- packages/data_taster/gemfiles/rails_7_0.gemfile.lock
- packages/data_taster/lib/data_taster/version.rb
Our upstream systems need a lower requirement for nokogiri.
- **Lower the requirement for nokogiri on data taster**
- **Release 0.4.2**
> Lower nokogiri requirement on data taster gemspec

- packages/two_percent/app/controllers/two_percent/scim_controller.rb
- packages/two_percent/spec/requests/scim_request_spec.rb
Includes `id` in SCIM attributes instead of filtering it out.
> Include id in scim attributes

- packages/data_conduit/Gemfile.lock
- packages/data_conduit/bin/console
- packages/data_conduit/docs/CHANGELOG
- packages/data_conduit/lib/data_conduit/adapters/trino_repository.rb
- packages/data_conduit/lib/data_conduit/version.rb
- packages/data_conduit/spec/data_conduit/adapters/trino_repository_spec.rb
Improve the way TrinoAdapter accepts query condition keys.
Today it requires a Sequel obj as key: conditions = { Sequel[:trx_month] => start_date..end_date }
Update to support string keys in Nitro: conditions = { "trx_month" => start_date..end_date }
[Runway story](https://runway.powerhrg.com/backlog_items/ORA-950)
> [Nexus][ORA-950] Improve params handling on Nitro queries
